# Generated by Django 2.2 on 2021-08-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_auto_20210820_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='users_who_like',
        ),
        migrations.AddField(
            model_name='quote',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to='books_app.User'),
        ),
    ]
